project:
  type: website
  output-dir: docs
website:
  title: "Cecilia Chen"
  description: "Graduate student in Social Data Analytics at UT Dallas."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - text: Assignments
        menu:
          - assign01.qmd
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/chen-cecilia
      - icon: envelope
        href: mailto:dal801123@utdallas.edu
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true